#!/bin/bash
VNOMAD="${1:-1.9.3}"

case `uname -m` in  
	aarch64|arm64) ARCH=arm64;;
	x86_64) ARCH=amd64;;
esac

case `uname -s` in
	Darwin) OS=darwin;;
	Linux) OS=linux;;
esac

echo "curl -L -o nomad_${VNOMAD}_${OS}_${ARCH}.zip https://releases.hashicorp.com/nomad/${VNOMAD}/nomad_${VNOMAD}_${OS}_${ARCH}.zip"

if test ! -f nomad_${VNOMAD}_${OS}_${ARCH}.zip
then
 curl -L -o nomad_${VNOMAD}_${OS}_${ARCH}.zip https://releases.hashicorp.com/nomad/${VNOMAD}/nomad_${VNOMAD}_${OS}_${ARCH}.zip
fi
unzip -o nomad_${VNOMAD}_${OS}_${ARCH}.zip nomad
./nomad version  

read -n1 -p "Proceed with test nomad ${VNOMAD} ${ARCH} ? (y = yes) " -r approval
echo
if [[ "$approval" =~ [Yy] ]]
then 
 echo OK
 screen -c .screenrc
else 
 echo Abort Abort Abort Abort Abort
fi
